name: Jenn Frost
favicon: null
layout_spectrum: 0.9361702
typography_spectrum: 0.7106383
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cc953e'
    - '#291900'
    - '#67583a'
    - '#856d42'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
