layout_spectrum: 0.9361702
name: Jenn Frost
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4202555
  lightness: 0.1235891
  saturation: 0.4962502
  rhythmicContrast: 0.0925059
  brandColors:
    - '#010000'
    - '#CE9441'
    - '#423928'
    - '#D1AA89'
    - '#8A867D'
typography_spectrum: 0.7106383
